Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -13,3 +13,7 @@ jobs:
         python-version: "3.10"
     - name: Install dependencies
       run: python .github/workflows/validate.py
+    - name: Exit with error
+      run: |
+        echo "Erroring"
+        exit 1
